version: 0.0
os: linux
files:
  - source: target/ROOT.war
    destination: /home/ec2-user/javaapp
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root